name: CI

on:
  push:
    branches: [ master ]

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploying the static website to gh-pages
      run: npm run deploy
